default = {'Hm': [4.5, 5.8],
           'Hb': [12, 17],
           'Ht': [37, 54],
           'VCM': [79, 97],
           'HCM': [26, 32],
           'CHCM': [31, 36],
           'RDW': [12, 15],
           'Leucócitos': [4000, 11000],
           'Segmentados': [37, 73],
           'Eosinófilos': [1, 7],
           'Linfócitos': [20, 50],
           'Monócitos': [1, 12],
           'Basófilos': [2],
           'Plaquetas':	[150000, 450000],
           'Creatinina': [1.3],
           'Uréia': [50],
           'Sódio': [135, 145],
           'Potássio': [3.5, 5.5],
           'Cálcio_Sérico': [8.8, 10.4],
           'Magnésio': [1.7, 2.6],
           'Albumina': [3.5, 5.2],
           'Bili_Total': [2],
           'Bili_Direta': [1],
           'Bili_Indireta': [1],
           'TGO_(AST)': [38],
           'TGP_(ALT)': [41],
           'Fosfatase_Alc.': [65, 300],
           'Gama-GT': [11, 50],
           'INR': [0.8, 1.2],
           'TTPA': [25, 34],
           'TAP': [12, 18],
           'TSH': [0.4, 4.5],
           'T4_Livre': [0.7, 1.8],   
           }

espelho = { 'Hm': ['Hm'],
            'Hb': ['Hb'],
            'Ht': ['Ht'],
            'VCM': ['VCM', 'VGM'],
            'HCM': ['HCM', 'HGM'],
            'CHCM': ['CHCM'],
            'RDW': ['RDW'],
            'Reticulócitos': ['Reticulócitos', 'Reti'],
            'Leucócitos': ['Leucócitos', 'Leuco'],
            'Blastos': ['Blastos'],
            'Promielócitos': ['Promielócitos'],
            'Mielócitos': ['Mielócitos'],
            'Metamielócitos': ['Metamielócitos'],
            'Bastões': ['Bastões', 'Bast'],
            'Segmentados': ['Segmentados', 'Neut Segmentados', 'Neut', 'Neutrófilos'],
            'Eosinófilos': ['Eosinófilos', 'Eos', 'Eosi'], 
            'Linfócitos': ['Linfócitos', 'Linf', 'Linfo'],
            'Monócitos': ['Monócitos', 'Mono', 'Mon'],
            'Basófilos': ['Basófilos', 'Baso', 'Bas'],
            'Linf._Atípicos': ['Atípicos'],
            'Plaquetas': ['Plaquetas', 'Plaq', 'Pqt'],
            'LDH': ['LDH', 'DHL'],
            'VHS': ['VHS', 'Hemossedimentação', 'Hemosse'],
            'PCR': ['PCR'],
            'Colest._Total': ['CT', 'Colesterol Total', 'ColesT', 'Col total'],
            'HDL': ['Hdl'],
            'LDL': ['Ldl'], 
            'Triglicérides': ['TGL', 'Triglicérides', 'Trigli'],
            'CPK': ['CPK'],
            'CPK-MB': ['CPKMB', 'CKMB'],
            'Troponina': ['Troponina', 'Tropo'],
            'BNF': ['BNF'],
            'Ferro': ['Ferro', 'Fe'],
            'Ferritina': ['Ferritina'],
            'Sat._Transf.': ['Transferrina', 'Transfer'],
            'TIBIC': ['TIBIC'],
            'B12': ['B12'],
            'Ác._Fólico': ['Fólico', 'Ácido Fólico'],
            'Creatinina': ['Creatinina', 'Creat', 'Cr'],
            'Uréia': ['Ureia'],
            'Clearance': ['CKDEPI', 'Glomerular', 'Clearance'],
            'Ácido_Úrico': ['Ácido Úrico', 'Úrico'],
            'Sódio': ['Na', 'Sódio'],
            'Potássio': ['K', 'Potássio'],
            'Fósforo': ['P', 'Fósforo'],
            'Cálcio_Sérico': ['Cálcio Sérico', 'Ca Sérico', 'Cálcio', 'Ca'],
            'Cálcio_Ionizável': ['Cálcio Ionizável', 'Ca Ionizável'],
            'Magnésio': ['Mg', 'Magnésio'],
            'Cloro': ['Cl', 'Cloro'],
            'Proteínas': ['Proteínas', 'Ptn', 'Prot'],
            'Albumina': ['Albumina', 'Alb', 'Albu'],
            'Globulina': ['Globulina', 'Glob', 'Globu'],
            'Relação_A/G': ['a/g'],
            'Bili_Total': ['Bt', 'Bilirrubina Total'],
            'Bili_Direta': ['Bd', 'Bilirrubina Direta'],
            'Bili_Indireta': ['Bi', 'Bilirrubina Indireta'],
            'TGO_(AST)': ['TGO', 'AST'],
            'TGP_(ALT)': ['TGP', 'ALT'],
            'Fosfatase_Alc.': ['FA', 'Fosfatase Alcalina'],
            'Gama-GT': ['GGT', 'GamaGT'],
            'Amilase': ['Amilase'],
            'Lipase': ['Lipase'],
            'INR': ['INR', 'RNI'],
            'TTPA': ['TTPA'],
            'Ratio': ['Ratio'],
            'TAP': ['TAP'],
            'TS': ['TS', 'Sangramento'],
            'TC': ['TC', 'Coagulação'],
            'Glicemia_Jejum': ['GJ', 'Glicemia', 'Jejum', 'Glicemia de Jejum', 'Glicose'],
            'Glicemia_Pós-P': ['GPP', 'Prandial'],
            'Glicada': ['Hemoglobina Glicada', 'HBA1C', 'Glicada'], 
            'TSH': ['TSH'],
            'T4_Livre': ['T4 Livre', 'T4L'],
            'Vitamina_D': ['VitD', '25OHD', 'Vitamina D', 'VitD-Direta']
            }

merger = {'Sérico': ['Sérico', 'Serico', 'Seri'],
          'Ionizável': ['Ionizável', 'Ion', 'Ionizavel'],
          'CT': ['CT'],
          'Total': ['Total'],
          'Livre:': ['Livre'],
          'Ureia': ['Ureia', 'Ur'],
          'Úrico': ['Urico', 'Uric'],
          'Ultra': ['Ultra'],
          'Urinário': ['Urinário', 'Urinária'],
          'Direta': ['Direta', 'Dir', 'Dir'],
          'Indireta': ['Indireta', 'Indi'],
          'VitD': ['VitD']
          }


lista_de_datas = []
lista_remover = list()
master = dict()